spring.application.name=thymeleaf

countries=India,China,Japan,Australia,Germany,Spain,France
languages=Java,Python,Angular,C++,C#,Java Script
systems=Microsoft Windows,Linux,MacOS,Android,IOS,Ubuntu
